Search.appendIndex(
    [
                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator",
            "name": "AbstractPdfCreator",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Return\u0020an\u0020unique\u0020type\u0020alias.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AisUsable\u0028\u0029",
            "name": "isUsable",
            "summary": "Check\u0020if\u0020all\u0020prerequisites\u0020for\u0020this\u0020bundle\u0020are\u0020fullfilled,\u0020typically\u0020check\u0020for\u0020installed\u0020libraries.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_isUsable"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetHtmlContent\u0028\u0029",
            "name": "getHtmlContent",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getHtmlContent"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetHtmlContent\u0028\u0029",
            "name": "setHtmlContent",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setHtmlContent"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_render"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetFilename\u0028\u0029",
            "name": "getFilename",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getFilename"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetFilename\u0028\u0029",
            "name": "setFilename",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setFilename"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetOutputMode\u0028\u0029",
            "name": "getOutputMode",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getOutputMode"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetOutputMode\u0028\u0029",
            "name": "setOutputMode",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setOutputMode"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetSupportedOutputModes\u0028\u0029",
            "name": "getSupportedOutputModes",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getSupportedOutputModes"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetFolder\u0028\u0029",
            "name": "getFolder",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getFolder"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetFolder\u0028\u0029",
            "name": "setFolder",
            "summary": "Absolute\u0020folder\u0020where\u0020to\u0020store\u0020pdf.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setFolder"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetMediaType\u0028\u0029",
            "name": "getMediaType",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getMediaType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetMediaType\u0028\u0029",
            "name": "setMediaType",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setMediaType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetFonts\u0028\u0029",
            "name": "getFonts",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getFonts"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetFonts\u0028\u0029",
            "name": "setFonts",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setFonts"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AaddFont\u0028\u0029",
            "name": "addFont",
            "summary": "Register\u0020a\u0020font\u0020file\u0020to\u0020the\u0020pdf.\u0020Should\u0020be\u0020ttf.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_addFont"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetMargins\u0028\u0029",
            "name": "getMargins",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getMargins"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetMargins\u0028\u0029",
            "name": "setMargins",
            "summary": "Set\u0020document\u0020margins.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setMargins"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetFormat\u0028\u0029",
            "name": "getFormat",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getFormat"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetFormat\u0028\u0029",
            "name": "setFormat",
            "summary": "Set\u0020the\u0020document\u0020format.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setFormat"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetOrientation\u0028\u0029",
            "name": "getOrientation",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getOrientation"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetOrientation\u0028\u0029",
            "name": "setOrientation",
            "summary": "Set\u0020orientation.\u0020Use\u0020AbstractPdfCreator\u003A\u003AORIENTATION_LANDSCAPE\u0020or\u0020AbstractPdfCreator\u003A\u003AORIENTATION_PORTRAIT.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setOrientation"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetTemplateFilePath\u0028\u0029",
            "name": "getTemplateFilePath",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getTemplateFilePath"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetTemplateFilePath\u0028\u0029",
            "name": "setTemplateFilePath",
            "summary": "Set\u0020the\u0020absolute\u0020path\u0020to\u0020a\u0020pdf\u0020template\u0020file.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setTemplateFilePath"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetBeforeCreateInstanceCallback\u0028\u0029",
            "name": "getBeforeCreateInstanceCallback",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getBeforeCreateInstanceCallback"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetBeforeCreateInstanceCallback\u0028\u0029",
            "name": "setBeforeCreateInstanceCallback",
            "summary": "Add\u0020an\u0020callback\u0020to\u0020modify\u0020constructor\u0020parameters\u0020for\u0020pdf\u0020library.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setBeforeCreateInstanceCallback"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetBeforeOutputPdfCallback\u0028\u0029",
            "name": "getBeforeOutputPdfCallback",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getBeforeOutputPdfCallback"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetBeforeOutputPdfCallback\u0028\u0029",
            "name": "setBeforeOutputPdfCallback",
            "summary": "Add\u0020an\u0020callback\u0020to\u0020modify\u0020the\u0020configuration\u0020or\u0020parameters\u0020before\u0020outputting\u0020the\u0020pdf\u0020file.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setBeforeOutputPdfCallback"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AgetLogger\u0028\u0029",
            "name": "getLogger",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_getLogger"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AsetLogger\u0028\u0029",
            "name": "setLogger",
            "summary": "Add\u0020a\u0020logger\u0020to\u0020the\u0020pdf\u0020library,\u0020if\u0020supported.",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#method_setLogger"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AOUTPUT_MODE_DOWNLOAD",
            "name": "OUTPUT_MODE_DOWNLOAD",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_OUTPUT_MODE_DOWNLOAD"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AOUTPUT_MODE_FILE",
            "name": "OUTPUT_MODE_FILE",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_OUTPUT_MODE_FILE"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AOUTPUT_MODE_INLINE",
            "name": "OUTPUT_MODE_INLINE",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_OUTPUT_MODE_INLINE"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AOUTPUT_MODE_STRING",
            "name": "OUTPUT_MODE_STRING",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_OUTPUT_MODE_STRING"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AOUTPUT_MODES",
            "name": "OUTPUT_MODES",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_OUTPUT_MODES"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AFONT_STYLE_REGUALAR",
            "name": "FONT_STYLE_REGUALAR",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_FONT_STYLE_REGUALAR"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AFONT_STYLE_ITALIC",
            "name": "FONT_STYLE_ITALIC",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_FONT_STYLE_ITALIC"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AFONT_STYLE_BOLD",
            "name": "FONT_STYLE_BOLD",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_FONT_STYLE_BOLD"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AFONT_STYLE_BOLDITALIC",
            "name": "FONT_STYLE_BOLDITALIC",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_FONT_STYLE_BOLDITALIC"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AORIENTATION_LANDSCAPE",
            "name": "ORIENTATION_LANDSCAPE",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_ORIENTATION_LANDSCAPE"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003AORIENTATION_PORTRAIT",
            "name": "ORIENTATION_PORTRAIT",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#constant_ORIENTATION_PORTRAIT"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024htmlContent",
            "name": "htmlContent",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_htmlContent"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024filename",
            "name": "filename",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_filename"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024outputMode",
            "name": "outputMode",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_outputMode"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024folder",
            "name": "folder",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_folder"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024mediaType",
            "name": "mediaType",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_mediaType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024fonts",
            "name": "fonts",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_fonts"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024margins",
            "name": "margins",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_margins"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024format",
            "name": "format",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_format"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024orientation",
            "name": "orientation",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_orientation"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024templateFilePath",
            "name": "templateFilePath",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_templateFilePath"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024beforeCreateInstanceCallback",
            "name": "beforeCreateInstanceCallback",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_beforeCreateInstanceCallback"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024beforeOutputPdfCallback",
            "name": "beforeOutputPdfCallback",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_beforeOutputPdfCallback"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\AbstractPdfCreator\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-AbstractPdfCreator.html#property_logger"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeCreateLibraryInstanceCallback",
            "name": "BeforeCreateLibraryInstanceCallback",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeCreateLibraryInstanceCallback.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeCreateLibraryInstanceCallback\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "BeforeCreateLibraryInstanceCallback\u0020constructor.",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeCreateLibraryInstanceCallback.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeCreateLibraryInstanceCallback\u003A\u003AgetConstructorParameters\u0028\u0029",
            "name": "getConstructorParameters",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeCreateLibraryInstanceCallback.html#method_getConstructorParameters"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeCreateLibraryInstanceCallback\u003A\u003AsetConstructorParameters\u0028\u0029",
            "name": "setConstructorParameters",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeCreateLibraryInstanceCallback.html#method_setConstructorParameters"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeCreateLibraryInstanceCallback\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeCreateLibraryInstanceCallback.html#method_getType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeCreateLibraryInstanceCallback\u003A\u003A\u0024constructorParameters",
            "name": "constructorParameters",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeCreateLibraryInstanceCallback.html#property_constructorParameters"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeCreateLibraryInstanceCallback\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeCreateLibraryInstanceCallback.html#property_type"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback",
            "name": "BeforeOutputPdfCallback",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html#method_getType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback\u003A\u003AgetLibraryInstance\u0028\u0029",
            "name": "getLibraryInstance",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html#method_getLibraryInstance"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback\u003A\u003AsetLibraryInstance\u0028\u0029",
            "name": "setLibraryInstance",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html#method_setLibraryInstance"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback\u003A\u003AgetOutputParameters\u0028\u0029",
            "name": "getOutputParameters",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html#method_getOutputParameters"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback\u003A\u003AsetOutputParameters\u0028\u0029",
            "name": "setOutputParameters",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html#method_setOutputParameters"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback\u003A\u003A\u0024libraryInstance",
            "name": "libraryInstance",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html#property_libraryInstance"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback\u003A\u003A\u0024outputParameters",
            "name": "outputParameters",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html#property_outputParameters"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\BeforeOutputPdfCallback\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-BeforeOutputPdfCallback.html#property_type"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator",
            "name": "MpdfCreator",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator\u003A\u003AisUsable\u0028\u0029",
            "name": "isUsable",
            "summary": "Check\u0020if\u0020all\u0020prerequisites\u0020for\u0020this\u0020bundle\u0020are\u0020fullfilled,\u0020typically\u0020check\u0020for\u0020installed\u0020libraries.",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html#method_isUsable"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html#method_render"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator\u003A\u003AgetSupportedOutputModes\u0028\u0029",
            "name": "getSupportedOutputModes",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html#method_getSupportedOutputModes"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Return\u0020an\u0020unique\u0020type\u0020alias.",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html#method_getType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator\u003A\u003AaddFontDirectories\u0028\u0029",
            "name": "addFontDirectories",
            "summary": "Add\u0020font\u0020directories\u0020to\u0020the\u0020config.\u0020Directory\u0020must\u0020contain\u0020mpdf\u002Dconfig.php.",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html#method_addFontDirectories"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator\u003A\u003AapplyFonts\u0028\u0029",
            "name": "applyFonts",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html#method_applyFonts"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator\u003A\u003AapplyDocumentFormatConfiguration\u0028\u0029",
            "name": "applyDocumentFormatConfiguration",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html#method_applyDocumentFormatConfiguration"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator\u003A\u003AapplyTemplate\u0028\u0029",
            "name": "applyTemplate",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html#method_applyTemplate"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\MpdfCreator\u003A\u003A\u0024legacyFontDirectoryConfig",
            "name": "legacyFontDirectoryConfig",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-MpdfCreator.html#property_legacyFontDirectoryConfig"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\TcpdfCreator",
            "name": "TcpdfCreator",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-TcpdfCreator.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\TcpdfCreator\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Return\u0020an\u0020unique\u0020type\u0020alias.",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-TcpdfCreator.html#method_getType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\TcpdfCreator\u003A\u003AisUsable\u0028\u0029",
            "name": "isUsable",
            "summary": "Check\u0020if\u0020all\u0020prerequisites\u0020for\u0020this\u0020bundle\u0020are\u0020fullfilled,\u0020typically\u0020check\u0020for\u0020installed\u0020libraries.",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-TcpdfCreator.html#method_isUsable"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\TcpdfCreator\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-TcpdfCreator.html#method_render"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete\\TcpdfCreator\u003A\u003AgetSupportedOutputModes\u0028\u0029",
            "name": "getSupportedOutputModes",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Concrete-TcpdfCreator.html#method_getSupportedOutputModes"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Exception\\MissingDependenciesException",
            "name": "MissingDependenciesException",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Exception-MissingDependenciesException.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Exception\\MissingDependenciesException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Exception-MissingDependenciesException.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Exception\\MissingDependenciesException\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Exception-MissingDependenciesException.html#method_getType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Exception\\MissingDependenciesException\u003A\u003AgetDependencies\u0028\u0029",
            "name": "getDependencies",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Exception-MissingDependenciesException.html#method_getDependencies"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Exception\\MissingDependenciesException\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Exception-MissingDependenciesException.html#property_type"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Exception\\MissingDependenciesException\u003A\u003A\u0024dependencies",
            "name": "dependencies",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-Exception-MissingDependenciesException.html#property_dependencies"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\PdfCreatorFactory",
            "name": "PdfCreatorFactory",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-PdfCreatorFactory.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\PdfCreatorFactory\u003A\u003AgetTypes\u0028\u0029",
            "name": "getTypes",
            "summary": "Return\u0020supported\u0020pdf\u0020creator\u0020types.",
            "url": "../classes/HeimrichHannot-PdfCreator-PdfCreatorFactory.html#method_getTypes"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\PdfCreatorFactory\u003A\u003AcreateInstance\u0028\u0029",
            "name": "createInstance",
            "summary": "Return\u0020a\u0020pdf\u0020creator\u0020instance\u0020for\u0020given\u0020type\u0020or\u0020null,\u0020if\u0020no\u0020type\u0020is\u0020registered\u0020for\u0020given\u0020type.",
            "url": "../classes/HeimrichHannot-PdfCreator-PdfCreatorFactory.html#method_createInstance"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\PdfCreatorFactory\u003A\u003AaddType\u0028\u0029",
            "name": "addType",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-PdfCreatorFactory.html#method_addType"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\PdfCreatorFactory\u003A\u003AgetPdfCreatorRegistry\u0028\u0029",
            "name": "getPdfCreatorRegistry",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-PdfCreatorFactory.html#method_getPdfCreatorRegistry"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\PdfCreatorFactory\u003A\u003A\u0024types",
            "name": "types",
            "summary": "",
            "url": "../classes/HeimrichHannot-PdfCreator-PdfCreatorFactory.html#property_types"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "../namespaces/default.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator",
            "name": "PdfCreator",
            "summary": "",
            "url": "../namespaces/heimrichhannot-pdfcreator.html"
        },                {
            "fqsen": "\\HeimrichHannot",
            "name": "HeimrichHannot",
            "summary": "",
            "url": "../namespaces/heimrichhannot.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Concrete",
            "name": "Concrete",
            "summary": "",
            "url": "../namespaces/heimrichhannot-pdfcreator-concrete.html"
        },                {
            "fqsen": "\\HeimrichHannot\\PdfCreator\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "../namespaces/heimrichhannot-pdfcreator-exception.html"
        }            ]
);
